from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

# Import DRF router
from rest_framework import routers
# Import your API ViewSet
from recipes.api_views import RecipeViewSet

def redirect_to_recipes(request):
    return redirect('recipes:recipe_list')

# Create a router instance
router = routers.DefaultRouter()
# Register your ViewSet with the router.
# The first argument is the URL prefix for this set of API endpoints.
# The second argument is the ViewSet class.
router.register(r'recipes', RecipeViewSet) # This will create URLs like /api/recipes/, /api/recipes/{id}/

urlpatterns = [
    path('', redirect_to_recipes, name='home'),  # Redirige la ruta raíz a recipes
    path('admin/', admin.site.urls),
    path('recipes/', include('recipes.urls')), # Your existing web app URLs

    # API URLs
    path('api/', include(router.urls)), # Include all URLs generated by the router under /api/
    # Optional: DRF login/logout views for the browsable API
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)