# Generated by Django 5.2.4 on 2025-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the recipe.', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the recipe. Optional.', null=True, upload_to='recipe_images/')),
                ('image_url', models.URLField(blank=True, help_text='Alternatively, provide a URL for the recipe image. Optional.', max_length=500, null=True)),
                ('ingredients', models.TextField(help_text='List all ingredients, separated by newlines or commas. Markdown formatting allowed.')),
                ('steps', models.TextField(help_text='Provide step-by-step instructions for preparing the recipe. Markdown formatting allowed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the recipe was added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the recipe was last updated.')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['title'],
            },
        ),
    ]
